[settings]
quiet = true

[hooks]
enter = "mise install"

[tools]
golang = "1.25"
golangci-lint = "latest"

[vars]
name = "github.com/lnrdll/ymr"

[tasks.init]
description = "(i) Init"
alias = "i"
dir = "{{ config_root }}"
run = '''
go mod init {{ vars.name }}
go mod tidy
'''

[tasks.clean]
description = "(c) Clean modules"
alias = "c"
dir = "{{ config_root }}"
run = "go clean -modcache"

[tasks.update]
description = "(u) Update all modules"
alias = "u"
dir = "{{ config_root }}"
run = '''
go get -u -t ./...
go mod tidy
'''

[tasks.run]
description = "(r) Run application locally"
alias = "r"
dir = "{{ config_root }}/cmd"
run = "go run main.go"

[tasks.lint]
description = "(l) Go Lint"
alias = "l"
dir = "{{ config_root }}"
run = "golangci-lint run -v"

[tasks.test]
description = "(t) Run unit tests"
alias = "t"
run = "go test -v -cover ./..."

[tasks.check]
description = "(ck) Run lint + tests"
alias = "ck"
run = [
  { task = "lint" },
  { task = "test" }
]

[tasks.build]
description = "(b) Build local binary"
alias = "b"
run = "CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -buildvcs=false -ldflags='-s -w -buildid=' -o ymr"
