version: "3"

tasks:
  build:
    desc: Build the binary
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ymr
  
  build::local:
    desc: Build the compiled binary
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: build
      - sudo mv ymr /usr/local/bin

  test:
    desc: Run tests
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - go test -v -cover ./...

  lint:
    desc: Lint the code
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - golangci-lint run -v

  update:
    desc: Update all modules
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - go get -u -t ./...
      - go mod tidy

  clean:
    desc: Clean modules
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - go clean -modcache

  mod:
    desc: Download and tidy Go Modules
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - go mod download
      - go mod tidy
