---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment # from-param: {{ .name }}-deployment
  labels:
    app: nginx # from-param: {{ .name }}
spec:
  replicas: 1 # from-param: {{ .replicas }}
  selector:
    matchLabels:
      app: nginx # from-param: {{ .name }}
  template:
    metadata:
      labels:
        app: nginx # from-param: {{ .name }}
    spec:
      containers:
        - name: nginx-container # from-param: {{ .name }}-container
          image: nginx:1.26.1-alpine # from-param: {{ .image }}
          ports:
            - containerPort: 80
          resources: # from-param: {{ .resources }}
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 200m
