apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/binary-authorization: default
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: "5" # from-param: {{ .maxScale }}
    run.googleapis.com/minScale: "0" # from-param: {{ .minScale }}
  labels:
    alias: test
    cloud.googleapis.com/location: us-central1
    component: utils
    context: platform
    element: serverless
    goog-terraform-provisioned: "true"
    service: operations
  name: test
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/sessionAffinity: "false"
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80 # from-param: {{ .concurrency }}
      containers:
      - env: # from-param-merge: {{ .envVars }}
        - name: FOO
          value: BAR
        image: image/test:2025.10.17 # from-param: location/to/docker/image/service:{{ .version }}
        name: jira2gcal-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: sa-test@gcp-example.iam.gserviceaccount.com # from-param: {{ .serviceAccount }}
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
