apiVersion: ymr/v1
kind: Config

# A list of templates to process.
# Paths are relative to the location of this spec.yaml.
templates:
  - example/gcp-cloud-run-local/service.yaml

# A simple list of target environments.
targetIds:
  - dev
  - prd

# A list of parameter sets.
parameters:
  # --- Shared values for dev and prd ---
  - values:
      concurrency: 250
    targetId: # Which targets this value set applies to
      - dev
      - prd

  # --- Dev-specific values ---
  - values:
      minScale: 1
      serviceAccount: my-service-account@dev-project.iam.gserviceaccount.com
      version: 2025.11.17
      envVars:
        - name: HELLO
          value: world
    targetId:
      - dev

  # --- Prod-specific values ---
  - values:
      minScale: 3
      serviceAccount: my-service-account@prd-project.iam.gserviceaccount.com
      version: 2025.10.17
    targetId:
      - prd
